spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/minicampus
    username: minicampus_user
    password: a0000

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true